name: "Slack notifications"
description: "Slack notifications"
author: "DevExpress"
inputs:
  hook:
    description: Slack hook URL.
    required: true
  alerts:
    description: Alerts JSON string.
    required: true
  commit_oid:
    description: commit oid.
    required: true
runs:
  using: "node16"
  main: "../../../slack-action.js"
