name: "Slack notifications"
description: "Slack notifications"
author: "DevExpress"
inputs:
  alerts:
    description: Alerts JSON string.
    required: true
runs:
  using: "node16"
  main: "../../../slack-action.js"
