name: "CodeQL: Finish"
description: "Finalize CodeQL database"
author: "GitHub"
inputs:
  check_name:
    description: The name of the check run to add text to.
    required: false
runs:
  using: "node16"
  main: "./slack-action.js"
