name: Notify Teams
description: Send Teams notifications

inputs:
  hook_url:
    description: 'URL of MS Teams hook'
    required: true
  bearer_token:
    description: 'Github token'
    required: false
  only_on_push:
    description: 'Enable on push event only'
    default: 'true'
    required: false
  alerts:
    description: 'Alerts JSON array'
    required: false

runs:
  using: node16
  main: dist/main.js
